# Generated by Django 5.1.15 on 2026-01-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_dosen_nidn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('short', models.CharField(blank=True, max_length=255)),
                ('full', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='akademik/')),
            ],
            options={
                'verbose_name_plural': 'Akademik',
            },
        ),
    ]
